output:
  output_dir: ./output
yuanbao:
  opencli_path: opencli/dist/main.js
  timeout: 600
  think: true
  search: false
  delay_min: 1
  delay_max: 15
zhipu:
  api_key: 203e6eb967864f89a36724fcde961041.y3TPy7eCZRtIzVeS
  model: glm-4-plus
  timeout: 600
  delay_min: 0
  delay_max: 0
deepseek:
  api_key: sk-4ee1a17d0d2f47009a5fa1379e582fc9
  model: deepseek-reasoner
  timeout: 600
  delay_min: 0
  delay_max: 0
image_gen:
  enabled: true
  chromedriver_dir: ./chromedriver
  timeout: 120
